name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build libncore
      run: |
           curl -OL https://ziglang.org/download/0.16.0/zig-x86_64-linux-0.16.0.tar.xz
           tar -xvf zig-x86_64-linux-0.16.0.tar.xz
           ./zig-x86_64-linux-0.16.0/zig build -Dtarget=aarch64-linux-android -Doptimize=ReleaseSafe -Dndk-sysroot=$ANDROID_HOME/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/sysroot
       
    - name: Upload lib
      uses: actions/upload-artifact@v4
      with:
        name: libncore
        path: zig-out/lib/*.so

    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: ncore
        path: zig-out/bin/*
